aspnetservice:
  ports:
  - 5000:5000/tcp
  environment:
    ConsulHost: consulagent
    rancher: host
  external_links:
  - Consul/consulagent:consulagent
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: rogeralsing/aspnetconsul
  stdin_open: true