consul2:
  ports:
  - 8301:8301/tcp
  - 8301:8301/udp
  - 8302:8302/tcp
  - 8302:8302/udp
  - 8400:8400/tcp
  - 8500:8500/tcp
  - 8600:8600/tcp
  environment:
    CONSUL_LOCAL_CONFIG: '{"start_join": ["consul1"],"rejoin_after_leave": true, "ui": true, "server": true, "data_dir": "/var/consul/data","ui_dir": "/var/consul/ui"}'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.requested_ip: 10.42.194.101
  tty: true
  command:
  - agent
  - -advertise
  - 10.42.194.101
  hostname: consulserver2
  image: consul:latest
  links:
  - consul1:consul1
  stdin_open: true
consul3:
  ports:
  - 8301:8301/tcp
  - 8301:8301/udp
  - 8302:8302/tcp
  - 8302:8302/udp
  - 8400:8400/tcp
  - 8500:8500/tcp
  - 8600:8600/tcp
  environment:
    CONSUL_LOCAL_CONFIG: '{"start_join": ["consul1"],"rejoin_after_leave": true, "ui": true, "server": true, "data_dir": "/var/consul/data","ui_dir": "/var/consul/ui"}'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.requested_ip: 10.42.194.102
  tty: true
  command:
  - agent
  - -advertise
  - 10.42.194.102
  hostname: consulserver3
  image: consul:latest
  links:
  - consul1:consul1
  stdin_open: true
consul1:
  ports:
  - 8301:8301/tcp
  - 8301:8301/udp
  - 8302:8302/tcp
  - 8302:8302/udp
  - 8400:8400/tcp
  - 8500:8500/tcp
  - 8600:8600/tcp
  environment:
    CONSUL_LOCAL_CONFIG: '{ "bootstrap": true,"rejoin_after_leave": true, "ui": true, "server": true, "data_dir": "/var/consul/data","ui_dir": "/var/consul/ui"}'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.requested_ip: 10.42.194.100
  tty: true
  command:
  - agent
  - -advertise
  - 10.42.194.100
  hostname: consulserver1
  image: consul:latest
  stdin_open: true
