consul1:
  ports:
  - 8400:8400/tcp
  - 8500:8500/tcp
  - 8600:8600/tcp
  - 8301:8301/tcp
  - 8301:8301/udp
  - 8302:8302/tcp
  - 8302:8302/udp
  environment:
    CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
  labels:
    io.rancher.container.pull_image: always
  tty: true
  command:
  - agent
  - -server
  - -bootstrap-expect=3
  - -ui
  hostname: consulserver1
  image: consul:latest
  stdin_open: true

consul2:
  ports:
  - 8400:8400/tcp
  - 8500:8500/tcp
  - 8600:8600/tcp
  - 8301:8301/tcp
  - 8301:8301/udp
  - 8302:8302/tcp
  - 8302:8302/udp
  environment:
    CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
  labels:
    io.rancher.container.pull_image: always
  tty: true
  command:
  - agent
  - -server
  - -bootstrap-expect=3
  - -retry-join=consul1
  hostname: consulserver2
  image: consul:latest
  stdin_open: true
  links:
  - consul1

consul3:
  ports:
  - 8400:8400/tcp
  - 8500:8500/tcp
  - 8600:8600/tcp
  - 8301:8301/tcp
  - 8301:8301/udp
  - 8302:8302/tcp
  - 8302:8302/udp
  environment:
    CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
  labels:
    io.rancher.container.pull_image: always
  tty: true
  command:
  - agent
  - -server
  - -bootstrap-expect=3
  - -retry-join=consul1
  hostname: consulserver3
  image: consul:latest
  stdin_open: true
  links:
  - consul1